manifest:
  remotes:
    - name: crides
      url-base: https://github.com/crides
  projects:
    - name: zmk
      remote: crides
      revision: cirque-trackpad
      import: app/west.yml
  self:
    path: config
