manifest:
  remotes:
    - name: jgreel
      url-base: https://github.com/jgreel
  projects:
    - name: zmk
      remote: jgreel
      revision: mouse-3.2-cirque
      import: app/west.yml
  self:
    path: config
