manifest:
  remotes:
    - name: jgreel
      url-base: https://github.com/jgreel
  projects:
    - name: zmk
      remote: jgreel
      revision: devel-mouse-pim447
      import: app/west.yml
  self:
    path: config
