file_format: "1"
id: trackpadtrackball
name: Trackpad Trackball
type: shield
url: https://github.com/jgreel/wearable_cirque_pim447
requires:
  - seeeduino_xiao_ble
  - pimoroni trackball_pim447
  - cirque pinnacle trackpad
features:
  - mouse
siblings:
  - cirquetrackpad
  - pimtrackball